# Generated by Django 3.1.5 on 2021-01-13 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htree', '0004_remove_pseudofs_content_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pseudofs',
            name='object_id',
        ),
        migrations.AlterField(
            model_name='pseudofs',
            name='fname',
            field=models.CharField(max_length=40, verbose_name='Имя файла/каталога'),
        ),
    ]
