# Generated by Django 3.1.5 on 2021-01-14 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('htree', '0007_pseudofs_is_child'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pseudofs',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pseudofs_children', to='htree.pseudofs', verbose_name='Родительский каталог'),
        ),
    ]
